on: [push]

jobs:
  build_nemoh_programs_with_docker:
    runs-on: ubuntu-latest
    name: A job to build
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build PDF
      id: build_pdf
      run: make docker_build_pdf
    - uses: actions/upload-artifact@v2
      with:
        name: frido
        path: |
          mazhe/Inter_*.pdf
