on: [push]

jobs:
  build_nemoh_programs_with_docker:
    runs-on: ubuntu-latest
    name: A job to build
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Nemoh programs
      id: build_nemoh
      run: make docker_build